# Generated by Django 4.0.4 on 2022-05-08 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='Категорія'),
            preserve_default=False,
        ),
    ]
