# Generated by Django 4.0.4 on 2022-05-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія для публікації', 'verbose_name_plural': 'Категорії для публікацій'},
        ),
    ]
